import { Pasien } from '@/model/models';

export const pasienPayload: Pasien = {
  no_rkm_medis: '',
  nm_pasien: '',
  no_ktp: '',
  penjamin: {
    no_kartu: 0,
    nm_asuransi: '',
  },
  jk: '',
  tmp_lahir: '',
  tgl_lahir: '',
  nm_ibu: '',
  alamat: '',
  gol_darah: '',
  pekerjaan: '',
  stts_nikah: '',
  agama: '',
  tgl_daftar: '',
  no_tlp: '',
  umur: '',
  pnd: '',
  keluarga: '',
  namakeluarga: '',
  kd_pj: '',
  no_peserta: '',
  kd_kel: '',
  kd_kec: '',
  kd_kab: '',
  pekerjaanpj: '',
  alamatpj: '',
  kelurahanpj: '',
  kecamatanpj: '',
  kabupatenpj: '',
  perusahaan_pasien: '',
  suku_bangsa: '',
  bahasa_pasien: '',
  cacat_fisik: '',
  email: '',
  nip: '',
  kd_prop: '',
  propinsipj: '',
};
